[players.MarcosTest1780429059]
nick = "MarcosTest1780429059"
raza = "Humano"
clase = "Mago"
mapa_id = 1
x = 11
y = 10
direction = 1
nivel = 1
vida = 240
vida_max = 240
mana = 450
mana_max = 450
experiencia = 0
oro = 0
constitucion = 300
inteligencia = 300
fuerza = 300
agilidad = 300

[players.Pepe]
nick = "Pepe"
raza = "Humano"
clase = "Mago"
mapa_id = 1
x = 10
y = 10
direction = 2
nivel = 1
vida = 240
vida_max = 240
mana = 450
mana_max = 450
experiencia = 0
oro = 0
constitucion = 300
inteligencia = 300
fuerza = 300
agilidad = 300

