[server]
host = "localhost"
port = "8080"

[window]
width = 800
height = 600
fullscreen = false
title = "Argentum Online"

[render]
tile_size = 32
assets_path = "assets/graficos"

[world]
map_width = 100
map_height = 100

[audio]
music_volume = 64
effects_volume = 96

[character]
nick = "Messi"
raza = "humano"
clase = "mago"