[server]
host = "localhost"
port = "8080"

[window]
width = 1024
height = 640
fullscreen = true
hud_panel_fraction = 0.30

[render]
tile_size = 32
assets_path = "assets/graficos"

[world]
map_width = 100
map_height = 100
map_name = "ciudad"

[mapas]
1 = "bosque"
2 = "mazmorra"
3 = "ciudad"
4 = "bosqueOscuro"
5 = "mazmorraInfinita"
6 = "orillaBosque"
7 = "orillaBosqueOscuro"

[audio]
music_volume = 64
effects_volume = 96

[ui]
font_path = "assets/fonts/Cardo-Bold.ttf"
font_size = 18

[character]
nick = "Messi"
raza = "humano"
clase = "mago"
